server.port=8080

# --- SQLite datasource (file will be created under working dir /data/app.db) ---
spring.datasource.url=jdbc:sqlite:D:/Softwares/sqlite/signals.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO

logging.file.name=logs/novaquant-app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

server.servlet.session.tracking-modes=cookie
